admin/environment-management/cvms.md, environments/cvms.md, manifest.json
This will replace the existing CVM article in the help center. We can follow-up this PR with cloud-specific deployment docs in the help center and link to them from here.
=> feat: add admin docs for CVMs

setup/installation.md
If namespace `coder` is used to deploy coder, the namespace should be set in `kubectl log` command.
=> Add missing namespace in kubectl command

environments/editors.md
[ch2111] warn users about low resources
The recommendation is to have at leat 8 Gb of RAM
and 4 cores available to run projector and IntelliJ
=> Add system requirements for JetBrains editors

admin/environment-management/cvms.md
This label already existed for Env docs, but didn't for CVMs.
=> chore: Apply Alpha label to Admin CVMs

admin/devurls.md
This replaces the command we call out in the `devurls` setup as we are saying we are modifying helm, but then run the `install` command. This changes it to an `upgrade`, and adds the repo.
=> Replace helm command with upgrade and specify repo

.github/workflows/deploy-preview.yaml
my latest two prs (#97 and #94) did not run the action. I wasn't sure if it was intentional or not to disable previews from forks.
ref: https://futurestud.io/tutorials/github-actions-run-on-pull-request
We could potentially limit to PRs against master.
=> attempt to fix deploy previews on forks

comparison.md, setup/configuration.md, setup/index.md
- As someone evaluating Coder, I should know that Coder has a 60 day trial license that can be immediately generated on https://coder.com/trial
- As someone evaluating Coder, I should know that Coder has a "local preview" option that is documented [here](https://codercom-km0xqlzsl.vercel.app/docs/setup/kubernetes/local-preview) (#68) and does not require a license.  
I am thinking that this info should probably be root level with some text in the [Setup](https://coder.com/docs/setup) page so the user doesn't have to do a lot of clicking around. Let me know if you think another hierarchy would be better.
I like how Okteto does this: https://okteto.com/docs/enterprise/install/overview.
⚠️ Do not merge until #68 is merged.
=> add info about trying coder

environments/personalization.md
hey @khorne3 - i noticed that the ~/personalize script will abort if there is no -y flag when a command is run. i added the following lines to clarify this for users. let me know what you think.
=> clarify personalize commands

.github/workflows/preview.yaml
`pull_request` was added as an event type to trigger deploys to preview from forks to assist with the OSS contribution process. Unfortunately, we depend on a secret to access a private repository which is NOT passed to the fork for security purposes (GitHub security enforces this). Therefore, I'm removing the `pull_request` event entirely which should fix the issues we were seeing.
Note: Pushes to branches in PRs will still trigger builds
=> Fix: Remove `pull_request` event from preview deploys

setup/installation.md
admin reset password link was redirecting to the help center. updated the link to redirect to the admin password reset on `docs`.
=> fix: pwd reset link

setup/kubernetes/local-preview.md
Added a space between where Dev URLs were written as DevURLs in order to make them consistent with how they are treated elsewhere.
=> Consistency of Dev URL treatment

setup/index.md
[related clubhouse story](https://app.clubhouse.io/coder/story/8839/add-nav-aids-to-setup-index)
added some context for users landing on the setup index page. however, the Kubernetes & install docs I linked are duplicated on the below tiles - so I'd like some feedback as to how we should proceed here.
=> chore: add nav aids to setup index [ch8839]

cli/installation.md
added a bit more clarity re: installation while still being (mostly) OS-agnostic
=> chore: clarify CLI install

setup/kubernetes/aws.md
Just went through the install the kube-system had no signs of calico but the shiny new calico-system namespace was full of goodies.
=> Calico uses calico-system namespace now

guides/ssl-certificates/cloudflare.md
This was discovered when helping a trial user debug setting up SSL certificates.
Proper indentation reference: https://cert-manager.io/docs/configuration/acme/#match-labels
=> fix indentation error in Cloudflare docs

admin/workspace-providers/deployment.md, setup/installation.md, setup/updating.md
For [CH#2927](https://app.clubhouse.io/coder/story/2927/document-database-superuser-requirement)
=> chore: add superuser requirement

admin/workspace-providers/deployment.md, changelog/1.13.2.md, environments/devurls.md
We refer to Developer URLs as two words, both capitalized: `Dev URL(s)`. I found various cases where the two words were combined into one, which is inconsistent with most other cases and the product UI.
=> fix(docs): Consolidate Dev URL(s) naming

setup/kubernetes/aws.md, setup/kubernetes/google.md
adding deploy timeline estimates for AWS & GCP, to keep with timeline currently included on Azure docs. also will be helpful in giving context to customers who are new to K8s.
=> add: cluster deploy timelines

admin/git.md
adding this clarification, as it's come in up a [slack thread](https://codercom.slack.com/archives/C014JH42DBJ/p1616584356048200) that users can utilize any git provider, as long as they manage their own SSH keys. users are only limited to the three listed git providers if they expect to configure a git integration via OAuth.
=> clarify supported git providers

setup/kubernetes/azure.md, setup/kubernetes/google.md
did some reading on network policy stuff, and learned that google enables Calico by default when `enable-network-policy` is included in the create cluster command. added this clarification for GCP.
additionally, azure has built-in support for calico, and users can _only_ enable it upon cluster creation. added this clarification
as well, since we make no mention of Calico, outside of the `network-policy "calico"` line in the create cluster command.
open to thoughts & feedback.
=> clarify network policy implementations

.github/workflows/preview.yaml
Show the commit hash of the HEAD of the pull request, rather than
${{ github.sha }}, which is a strange internal hash.
=> chore: use hash of pull request head in preview message

.prettierrc, manifest.json, package.json, scripts/add_clog_to_manifest.ts, scripts/create-clog.sh, tsconfig.json, yarn.lock
In c886756b2783d1289eaaf96b950c05d02585e26b a clog generation script was added in order to help automate changelog generation. However, generated clogs still needed to be manually added to `manifest.json`. At the time, use of `jq` was experimented with in the `create-clog.sh` script, but was found to be not worth the effort.
Adds a NodeJS script written in TS for adding changelog entries to `manifest.json`.
The `manifest.json` file was formatted as part of this diff because the `add_clog_to_manifest.ts` script uses `JSON.stringify` to serialize changes to JSON. The resulting format differed from our prior format, but still complies with prettier.
```console
$ ./scripts/create-clog.sh --version=1.18.2 --release-date=$(date +%D)
Creating template using version: 1.18.2 and release date: …
```
=> chore: Automate adding clog to manifest

.github/workflows/ci.yaml, package.json
Use the same script names (e.g. yarn format:write) as we do in
the monorepo, so that it's easier to switch between projects.
=> chore: use the same linter settings as the monorepo

setup/requirements.md
Adding CNI requirement to Setup > Requirements, as customers have deployed Coder without network policies enforced, leading to surprises about security holes in their clusters.
Open to edits & feedback.
[Clubhouse story](https://app.clubhouse.io/coder/story/9751/document-network-policy-requirement)
=> Document network policy requirement [ch9751]

setup/kubernetes/google.md
updating node type to `n1-highmem-4` as it better supports the use of CVMs and removes scale up issues during env builds. uses the same amount of vCPUs as the prior `n1-standard-4` just with added memory. 
we've seen customers deploy via our happy path and realize they need a bigger node after the fact. hopefully this will avoid that issue.
=> update GCP node type in create cluster command

setup/kubernetes/google.md
adding these edits to make it clearer to the reader that there are two options when deploying a GKE cluster.
=> clarify GKE cluster options

package.json, yarn.lock
Context:
In #233 it was observed that we allow @types/node in LTS 14, but that
due to operational/architectural issues of cdr/docs and cdr/m, we should
instead consistently use version 12 of node.
Details:
- Set engines.node version to "^12.16.0". This is equivalent to the
version used in cdr/m. Note that in npm, the caret means that the
latest minor and patch versions are OK - meaning 12.21.x is compatible
with ^12.16.0
- Use the latest version of @types/node, with a caret to indicate minor
and patch versions are compatible
Resolves: #244
=> chore: Pin to node 12

.github/PULL_REQUEST_TEMPLATE/release-template.md, .markdownlintignore
Theoretically, this PR template should only apply if using the query param `?template=release-template.md` - at least from what I gather when reading https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
I want to ensure normal PRs don't have this information autofilled, but alas I'm unsure how to proceed without actually merging it first
=> chore: Add release pr template

scripts/create-clog.sh
---
```console
$ ./scripts/create-clog.sh --version=1.19.0 --release-date=$(date +%D)
Creating template using version: 1.19.0 and release date: 04/08/21
Calling add_clog_to_manifest.ts to update manifest.json
appending manifest.json with clog version:  1.19.0
Done
tip: run yarn fmt:fix to prettify manifest.json
tip: After comitting this branch visit
https://github.com/cdr/docs/compare/master...vapurrmaid/test-pr-template?template=release-template.md&expand=1
to open a PR using the release PR template
Done
```
=> chore: Print PR template link in create-clog.sh

setup/installation.md
adding link to the helm values `README` file in the installation section. right now, we basically say "edit the `values.yaml` file as needed" - without any context as to the configuration options available to users. ideally this will point users in the right direction, and give them a better understanding as to which values are relevant for their deployment needs.
=> add link to README with helm values

setup/updating.md
adding the following clarification:
`helm uninstall` will delete the timescale _instance_ that is internal to the cluster which Coder is deployed on, but the associated timescale _volume_ will remain intact.
this means any subsequent `helm install` will create a new timescale instance with the same data as the previous, due to the volume remaining intact.
please wordsmith as needed. thank you!
=> clarify timescale deletion

guides/ssl-certificates/cloudDNS.md, guides/ssl-certificates/route53.md, manifest.json
adding steps for configuring SSL for Coder via Google's Cloud DNS, referenced from [this doc](https://docs.google.com/document/d/1NahF4Mx5t_nLrwg7MZsyeSlMVnEIQi29v7poNl6LV8w/edit#).
i've completed a successful install for a customer using the linked doc, but it wouldn't hurt for someone else to dogfood it.
please see my comments below for line-specific thoughts.
=> add: Cloud DNS SSL config

admin/git.md, environments/preferences.md
adding context around our SSH keys. they're generated using the ECDSA algorithm, which is different than the commonly used RSA. this can affect which git providers customers use.
=> specify ECDSA use

guides/customization/vnc.md
VNC can only be accessed via Dev URLs if the image includes both a VNC server (tigerVNC) and a web client (noVNC). 
If you only have a server on the image, or want a potentially faster connection, you can connect via SSH port forwarding.
=> VNC: add local connection option and clarify web option

workspaces/workspaces-as-code/templates.md
the template fields in the WaC yaml file are case-sensitive, and won't populate correctly if case syntax is incorrect.
[related clubhouse story ch11430](https://app.clubhouse.io/coder/story/11430/update-wac-docs-stating-yaml-syntax-is-case-sensitive)
=> state yaml syntax case-sensitivity

guides/ssl-certificates/cloudDNS.md
the command to generate the private key from the GCP service account was missing the `iam`, as documented [here](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/create)
=> fix: private key command

admin/workspace-providers/deployment.md
adding the `--namespace` flag to the various workspace provider-related commands, as it can spell trouble for those who run these commands in the wrong namespace. open to thoughts, feedback.
related clubhouse story [ch11641](https://app.clubhouse.io/coder/story/11641/workspace-provider-namespace-called-coder-in-docs-creates-confusion-add-namespace-to-helm-upgrade)
=> update wp commands with namespace

guides/admin/helm-charts.md, setup/installation.md, setup/updating.md
removing "optional" from the `helm get values` command, as saving the current `values.yaml` file is quite important for retaining a Coder configuration across upgrades and troubleshooting any upgrade-related errors.
additionally, there were some inconsistencies with the upgrade commands & use of custom `values.yaml` files, so I cleaned those up.
=> remove optional flag & make commands consistent

guides/ssl-certificates/cloudDNS.md, guides/ssl-certificates/cloudflare.md, guides/ssl-certificates/route53.md
I often refer to this troubleshooting guide to see where certificate requests go wrong (e.x invalid API key, incorrect formatting, bad secret name, no annotation added).
=> add links to cert-manager troubleshooting

setup/kubernetes/local-preview.md
adding note that local preview automatically uploads a single-seat user license. will be helpful context for customers who unknowingly create additional users and run into the "license limit reached" screen.
=> clarify local preview licensing

workspaces/workspaces-as-code/index.md, workspaces/workspaces-as-code/templates.md
adding updates to WaC stuff:
- change template version to `0.2`
- clarify support for both `.yaml` & `.yml`
- replace `coder.yaml` with `<template-name.yaml>`
=> update: WaC template version & file naming

workspaces/personalization.md
Add a sentence explaining that the install.sh must be marked executable and that coder won't do it for you.
I was assuming that coder would mark as executable anything it intended to execute.  That is not the case.
=> Explain install.sh must be executable

setup/kubernetes/aws.md
With some shells, variables cannot be directly set in the same command
see: https://gist.github.com/bpmct/f4b697c1bd2861f8a5d6766897ace8e1
=> set AWS cluster variables in separate command

admin/access-control/password-reset.md
This is also a more-reliable way to get the initial admin password, as it can sometimes be lost in the logs after an install. A one-liner makes it easier to quickly fetch the password, while still documenting what is being ran.
=> add one-liner for password reset

workspaces/workspaces-as-code/templates.md
The current `gpuCount` is not correct and it should be `gpu-count`.
Asking @Emyrk to review as we may be making additional changes to stay consistent, but for now I want to verify that I have things right in the template 👍
=> Correct `gpu-count` on WAC templates

.spelling, admin/workspace-management/cvms.md
@kylecarbs and I just debugged an issue with a customer that was trying to use CVMs with `NFS` for a file system. This is not supported by CVMs and needs to be called out.
@khorne3 my only thing to add here potentially is changing the format of the `Note` since there's two `Note:` blocks now:
=> Add CVM limitation on file systems

.github/dependabot.yml, .github/workflows/preview.yaml
The upstream author publishes updates to this action using the same
scheme as GitHub, where the v2 tag is updated to the latest release
of the 2.x series. Therefore, we can manage updates manually.
=> chore: ignore updates to marocchino/sticky-pull-request-comment

setup/requirements.md
adding storage requirement info, specifically around the use of PVCs and block storage. also reiterating our recommendation of using an external PostgreSQL instance for production deploys, and noting the minimum version required.
open to feedback & word-smithing.
=> add storage & db requirements

guides/ssl-certificates/cloudDNS.md
Fix typo in variable name (`ingress.tls.devurlsHostSecretName`) and change variable value from array to object (`ingress.annotations`).
=> Fix helm variable names in CloudDNS docs

workspaces/workspaces-as-code/templates.md
This will need to be polished when 1.19 goes out. Just starting it now for internal use.
0.2 update adds `policy` and `value` fields as well
as `spec` -> `specs`
=> [1.19] WAC Docs 0.2 yaml template update

guides/deployments/archive-install.md, manifest.json, setup/installation.md
adding steps for pulling down the helm chart & installing Coder in an archive, as a customer has run into this issue. @sreya provided the steps (included in this PR) as a solution to the customer.
=> add steps for installing coder in an archive

.github/workflows/ci.yaml, .github/workflows/preview.yaml
Update the branch names from master to main for the GitHub Actions
workflows. (Closes: #245)
Once this is approved, I will rename the default branch from master to main and then merge this change.
=> chore: update workflows to build from main

cli/remote-terminal.md, workspaces/ssh.md
Update documentation to reflect the preferred usage of our shell
invocation command, coder ssh. The coder sh command is an alias
to this command.
=> fix: update coder sh to ssh

guides/deployments/postgres.md
We require low latency between Coder and the database, so update
the PostgreSQL installation guide to indicate that fact.
=> fix: describe database latency requirements

guides/ssl-certificates/route53.md
updating the `helm install` command on Route53 docs to remove the now deprecated `additionalAnnotations` value and replace with `annotations`.
=> update Route53 annotation value

admin/workspace-providers/deployment.md, workspaces/variables.md
Context: I remember we removed `--force` from our standard update as it was constantly failing the update as described here: https://coder.com/docs/setup/updating#fixing-a-failed-upgrade: https://github.com/cdr/docs/pull/171
When updating my workspace provider, I ran into similar errors and my deployment succeeded without the command. I'm not exactly sure why, but I believe remember seeing `--force` only leads to a successful install on specific versions of helm. A sanity check would help, though.
=> potential fix to workspace provider upgrade command

guides/ssl-certificates/azureDNS.md, guides/ssl-certificates/route53.md, manifest.json
docs for setting up SSL certificates using Azure DNS & cert-manager. Referenced documentation includes:
- [cert-manager Azure DNS docs](https://cert-manager.io/docs/configuration/acme/dns01/azuredns/)
- [aad-pod-identity docs](https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/)
please wordsmith & format where necessary.
=> feat: azure DNS config & ssl setup via cert-manager

setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md
calling out node types that support GPUs, by referencing each cloud provider's respective documentation. also briefly touching on node sizing, and referencing our Compute Resources guide.
=> call out GPU nodes

setup/requirements.md
This PR attempts to add some additional recommendations around sizing. A common ask of our customers is what size of a node (and how many nodes) they should have in their cluster for `x` number of developers.
This is very difficult to determine, as the work a developer is doing within their environment can vary greatly, requiring a different amount of resources. This PR addresses that with giving recommendations of initial sizing + measuring and iterating to right size it over time.
[ch13598]
@khorne3 I continued the "quote" block we had here, but the design of that may look weird with so much text in a "quote" block. Let me know if you'd like that pulled out into normal text or something else. 👍  See below screenshot of the large quote block:
=> chore: Add information re: cluster sizing reqs

guides/admin/oidc-azuread.md
The link to the OIDC page was broken. This should fix it.
=> Fix: Correct link to OIDC

setup/requirements.md
This just removes the `peak` terminology [as requested](https://github.com/cdr/docs/pull/390/files/0c396b66a47ab0672a6e5f7023cae5493ef76584#r647035656) to remove ambiguity.
=> chore: Remove "peak" from requirements

guides/ssl-certificates/cloudflare.md
Cloudflare guide has the user creating an `api-token`, but references an `api-key` in the `.yaml` files (which is a different Cloudflare authentication method than `api-token`). Making this change to prevent users from running into issues that are caused from this inconsistency.
=> change api-key to api-token

package.json, setup/installation.md
Pulling full values file from the helm chart has stuff like `cemanager.image` etc. which we don't want the user to have in their values file unless they are specifically pulling images from another registry.
=> Avoid pulling full values file during install

guides/ssl-certificates/azureDNS.md, guides/ssl-certificates/route53.md
same variable change as done in #348, while also adding quotations to the letsencrypt annotation.
=> fix: helm variable names, annotations for AzureDNS & Route 53

.github/workflows/ci.yaml, .github/workflows/preview.yaml
Restrict the GITHUB_TOKEN issued for builds to reads of respository
metadata and file contents.
=> chore: use minimal permissions for workflows

workspaces/workspaces-as-code/code-completion.md, workspaces/workspaces-as-code/index.md, workspaces/workspaces-as-code/templates.md
Changing product + docs to consistently refer to WAC as alpha
=> chore: change WaC status from beta to alpha

guides/ssl-certificates/cloudDNS.md
Updating step 5 to reflect that cluster-issuer automatically issues certs using values from `helm install` for the dev URL and host secret names.
~I think this will need to be changed on all the guides and will do so once we've verified that the proposed updates are correct.~ This is the only doc that we explained certs this way.
=> chore: update installation step for SSL certs guide

setup/air-gapped/index.md, setup/air-gapped/infrastructure.md
The cert application command needs to be a helm upgrade command rather than a kubectl get secret command.
=> Airgapped network instructions cert application command is wrong

images/writing.md
Context:
- Docker is now [installed in the base image](https://github.com/cdr/enterprise-images/blob/main/images/base/Dockerfile.ubuntu#L29-L30), there is no need for my custom docker-sandbox image
- Specific images that leverage the sysbox runtime at build time, cannot be currently be built inside a Coder workspace.
=> custom images: clarify building CVM images

manifest.json, setup/kubernetes/k3s.md
This PR documents the steps necessary to install a K3s cluster on an Ubuntu machine as an alternative to Local Preview (functioning SSH, dev URLs, works for prod use) or a managed Kubernetes solution.
Open questions:
- ~~This doc is currently Ubuntu-specific, but for no particular reason other than "it works." Should I test on some other operating systems or better describe requirements? The goal by mentioning the OS is that this works best on a new machine.~~
- ~~Can this have a better title to explain it's a good "single-host" solution versus managed Kubernetes~~
- ~~Are there any anti-patterns / inaccuracies?~~
- For multi-node use, is there anything else we should recommend (e.g an external load balancer)? k3s supports [multi-node …
=> add k3s cluster setup doc

guides/ssl-certificates/azureDNS.md, guides/ssl-certificates/route53.md
making this change to prevent untrusted certs from being used, and providing a sub-optimal TLS config experience for users.
=> update letsencrypt server URL to prod

.github/dependabot.yml
* Open pull requests for major version updates for GitHub Actions
* Ignore major version updates for Node.js types
=> chore: update dependabot version ignores

admin/workspace-management/cvms.md, guides/ssl-certificates/cloudflare.md, guides/ssl-certificates/route53.md, setup/kubernetes/aws.md, setup/kubernetes/index.md
Recommend that users track supported Kubernetes versions, and remove
the reference to version 1.13.
[ch13998]
=> chore: clarify version support policy

setup/kubernetes/aws.md
received an error when applying the Calico manifests, because it was missing the `Installation` kind. i've updated our docs with the commands from AWS' docs and I've confirmed they work properly.
=> update calico manifests in AWS docs

setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md, setup/kubernetes/k3s.md
adding a link to the SSL guides in the `Next Steps` section of the k8s pages. this should better integrate the SSL guides with our install docs.
i'm hoping we can further build out this `Next Steps` section to include a variety of deployment routes/paths one can take when installing Coder. open to thoughts/suggestions.
=> link SSL cert guides in next steps

admin/git.md, changelog/1.21.0.md, workspaces/preferences.md, workspaces/ssh.md
* Update 1.21 security release notes with details of ECDSA -> ED25519 algorithm change
* Update existing references to ECDSA where applicable.
* Drive-by: fix typo
=> Update references to ECDSA.

workspaces/workspace-templates/templates.md
configure script examples were missing the `value` piece. user sent in a zendesk ticket notifying us of this.
=> add `value` to configure script examples

.vscode/extensions.json, .vscode/settings.json
This repository recommends the `davidanson.vscode-markdownlint` extension and prompts the user to install it when they first clone the docs repo. However, the formatter will do nothing unless people set it to their default formatter and intermittently use the "format" command in the command palette or a keyboard shortcut.
This proposed PR will (for all users editing the docs with VS Code):
- set `davidanson.vscode-markdownlint` as the default formatter for this repo
- auto format (with this `davidanson.vscode-markdownlint`) whenever a file is saved
This should also lead to less linting issues from new contributors
Alternatives:
- document how someone can do this themselves on the README
I use the "prettier" extension for other projects and, while it always passes lint tests, it will try …
=> recommend default formatter and auto-format on save

setup/kubernetes/local-preview.md
Context: workspaces in networking v2 cannot dial to `localhost` as an access URL since they would technically be dialing themselves.
STUN support in future releases will solve this.
=> document localhost issue with local preview

guides/tls-certificates/cloudDNS.md
Context: The current docs do not work for someone using the version of cert manager we recommend. I ran into this while testing the cloud DNS docs on a new cluster
The old version we used to recommend works fine.
https://github.com/streamnative/charts/pull/135/files#diff-f446351342bdec56ed4dcd24f2fce3d14fee4c3c50c3bf92e07637b3fac885acL41-L42
=> cloud DNS docs: fix outdated dns01 solver name

setup/architecture.md
changes `manager` to `coderd` in the architecture docs.
=> update architecture naming

guides/troubleshooting/admin-pwd.md, guides/troubleshooting/docker-problems.md, guides/troubleshooting/git-oauth.md, guides/troubleshooting/inotify-watch-limits.md, manifest.json
adding steps to troubleshoot an error seen when attempting to retrieve or reset the admin pwd behind a proxy. also added a previous troubleshooting card (#540) to the manifest
=> add admin pwd reset troubleshooting & manifest updates

setup/air-gapped/index.md
@khorne3 How do we get this change back into the 1.21 docs?
=> Remove dashboard container from air-gapped

workspaces/devurls.md
documenting how to programmatically access authenticated dev URLs, per a customer inquiry. tested & validated on my end.
=> add programmatic dev URL access

admin/workspace-providers/deployment.md, admin/workspace-providers/index.md, setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md, setup/kubernetes/index.md, setup/kubernetes/k3s.md, setup/kubernetes/local-preview.md, setup/kubernetes/openshift.md
We currently link to https://coder.com/docs/coder/v1.21/setup/kubernetes/ in our hosted beta emails. These changes clarify that our cluster guides also work for workspace providers.
The Setup > Kubernetes page may not be as intuitive for discoverable for people using our hosted beta, but it can be discovered via the workspace providers docs. As hosted beta becomes more popular, we may need to move the Kubernetes docs outside of the normal flow of installing Coder to support these two use cases equally.
=> clarify: cluster guides are also for workspace providers

admin/workspace-management/cvms.md
making this change, as cached CVMs _do_ support registry authentication methods. this is an important distinction, as we have many customers that require registry authentication.
=> clarify CVM auth capabilities

setup/kubernetes/k3s.md
* Condense the copy in k3s install instructions
* Link to "local preview" page, since it refers to install methods
using both kind and Docker Desktop
=> chore: fix broken link to local preview

changelog/1.21.3.md, changelog/1.22.1.md, manifest.json
changelog for 1.22.1 + 1.21.3 (otherwise the 1.22 version of docs won't have this)
=> chore: add changelogs for 1.21.3 and 1.22.1

guides/admin/timescale-migration.md, guides/deployments/postgres.md, manifest.json, setup/installation.md
adding a guide for migrating data out of timescale and into an external postgreSQL instance. also includes cleans up existing db docs.
[ch12923]
=> add timescale migration & clean up postgres stuff

setup/kubernetes/google.md
When copy & pasting the gcloud command I was getting a failure about `us-central1-a` not being available in "default", it appears this was caused by using `$ZONE` in the subnetwork flag instead of `$REGION`.
This also fixes a deprecation warning for `--enable-stackdriver-kubernetes` which has been replaced by `--logging=SYSTEM,WORKLOAD`  and `--monitoring=SYSTEM`, see https://cloud.google.com/stackdriver/docs/solutions/gke/installing
=> Add region env variable & replace stackdriver flag

setup/kubernetes/local-preview.md
The "Dev URLs" section was accidentally nested under the Kind script.
=> move dev urls section in local preview docs

setup/installation.md
adding steps to troubleshoot external IP issues with EKS. setting the `externalTrafficPolicy` to `Cluster` resolves any LB health check failures typically seen with EKS.
I wanted to include this step in the EKS setup docs, but since this issue is seen _after_ Coder installation, I figured it'd be best to place this towards the end of the install steps, when users are attempting to access Coder via the external IP.
[ch17156]
=> add EKS troubleshooting steps

setup/updating.md
@khorne3 I know some of this is covered in the `admin/satellite/migration` page but I wanted to make it clear what the path to success is during upgrades. 
Please fix all the broken links. I'm not sure how cross-refs work in this SSG.
=> Add upgrade steps for 1.21

workspaces/variables.md
Although we renamed environments to workspaces, this ENV var
is still listed as CODER_ENVIRONMENT_NAME
=> fix(workspaces): name env variable

workspaces/editors.md
This fixes the `X-FRAME-OPTIONS` to be set to `same`. This is required to fix rstudio in 1.23. Any previous versions, this has no effect.
=> hotfix(rstudio): add correct frame options

setup/kubernetes/index.md, setup/kubernetes/local-preview.md
we need a workaround for when we have proper nouns in strings used for links; at this time, am disabling mdlint on those pages so all the tests stop failing.
=> chore: disable mdlint for select pages

workspaces/variables.md
Need to fill in the details of a few of them. Arranged them to match the output given by 
```
env | grep CODER_
```
=> fix(workspaces): add and arrange missing env vars

changelog/1.25.0.md
Add a notice indicating that this is the final release of Coder
that will support Kubernetes 1.19, in keeping with our version
support policy and the Kubernetes upstream release schedule.
=> chore: add Kubernetes support notice to changelog

admin/workspace-providers/deployment/ec2.md
changed cluster to instance and associated AMI initialism with upon first usage of Amazon Machine Image (technically we use AMI in the header lone line above before identifying it, but given the audience and usage I think that is ok)
=> EC2 clarifications

workspaces/editors.md
For some reason, there were carriage returns on steps 6, 7. Also changed the section title to state Gateway since that is the term prospects know who use JetBrains.
=> removed carriage returns and changed title to use industry term Gateway

admin/audit.md
Corrected connect action description to include local VS Code, JetBrains Gateway, ssh command, and Coder CLI coder ssh command.
Also corrected SSH action, removing that it covers local SSH ( connect action does ), and made reference that JetBrains Projector IDEs are not logged yet with this action.
=> corrected connect and SSH actions in audit

images/embed-button.md
pushing this change to make clear that a git OAuth integration is required for using embedded image buttons.
=> clarify embedded image button requirements

.github/workflows/build_coder_image.yaml
`tj-actions/changed-files` was not being used, so I removed it.
```
Error : .github#L1
tj-actions/changed-files@v2.1 is not allowed to be used in cdr/docs. Actions in this workflow must be: within a repository owned by cdr, created by GitHub, verified in the GitHub Marketplace or match the following: marocchino/sticky-pull-request-comment@*, styfle/cancel-workflow-action@*, w3f/action-find-old-files@*, 8398a7/action-slack@*.
```
Uses the proper image name as well.
=> fix: Coder image workflow wasn't working

workspaces/editors.md
In some deployments, this line is necessary to avoid an insecure redirect that prevents RStudio from rendering. In others, it will be harmless.
Since we don't maintain an RStudio image, I think this is the only area we need to change it. Let me know if I'm missing something.
=> fix: add line for RStudio on https deployments

admin/devurls.md, workspaces/devurls.md, workspaces/ssh.md
Updated dev URL docs to latest release behavior.
Also updated for better definitions of what dev URLs are, how they operate, consistency, clearer examples, current release screenshot, and better clarity with port forwarding.
Also mentioned constant suffix feature in 1.26.0
=> Devurl public definition

workspaces/preferences.md
Dark theme is now in Preferences as a section.  The Shell feature was not in the Account tab.
=> made dark theme and shell correction to preferences

setup/air-gapped/index.md
was skimming through the air-gapped docs and noticed a redundant paragraph. this PR cleans things up.
=> chore: remove redundant timescale note

workspaces/editors.md
I tried copying it but there are extra newlines that cause it to break.
```
Sending build context to Docker daemon  3.072kB
Error response from daemon: dockerfile parse error line 19: unknown instruction: HTTPS://DOWNLOAD2.RSTUDIO.ORG/SERVER/BIONIC/AMD64/RSTUDIO-SERVER-1.4.1717-AMD64.DEB
```
=> fix: rstudio dockerfile example

guides/tls-certificates/docker-tls.md
removing the `DEVURL_HOST` quotations in the Docker Compose file. a prospect reported this threw an error where unnecessary characters were added to newly created dev URLs.
=> fix: remove dev url var quotations

admin/access-control/password-reset.md, guides/troubleshooting/admin-pwd.md, setup/docker.md
Our password reset docs were for Kubernetes only. I added details in the Coder for Docker section. 
When searching "reset password," there is also a troubleshooting guide. I added a link that references the original instructions that aims to help users navigate to the correct page
=> fix: clarify password reset process

admin/workspace-management/process-logging.md
discovered a particular kernel configuration that is needed to successfully run the `exectrace` sidecar container:
- `CONFIG_DEBUG_INFO_BTF=y`
@deansheather let me know if we should include the command(s) to run to check for this on the host system.
=> add ebpf-required config

guides/deployments/podman.md
With the example deployment manifest for smarter-device-manager,
users need to label compatible nodes in order for the DaemonSet
to run.
=> chore: add missing node label step

setup/kubernetes/aws.md
updating our node group `yaml` to provision an EKS _managed_ node group, which will display the node group in the EKS console.
the former `yaml` spec did not do so.
=> chore: update managed node group yaml

.github/workflows/ci.yaml, .github/workflows/preview.yaml, .github/workflows/production.yml
Use GitHub's concurrency feature to cancel in-progress builds
on pull request events, and serialize builds for branch push
events.
=> chore: enforce concurrency with GitHub feature

setup/docker.md
@khorne3 we should wait until 1.28 to put this in. It _works_ in 1.27, but has some quirks I fixed.
=> feat(cdr): Docs for remote postgresql C4D

changelog/1.27.0.md, changelog/1.27.1.md
formatting is no longer broken:
=> chore: fix formatting in changelogs

changelog/1.28.1.md, manifest.json
might need to add mention re: relaxing K8s requirement ~(would also need to update 1.28.0 changelog so that it's not listed as a breaking change)~
=> chore: add 1.28.1 changelog

setup/requirements.md
adding context around `coderd` reqs/limits and replicas.
=> feat: coderd resource recommendations

.github/workflows/production.yml
Update the deployment to use Vercel Deployment hooks. Also, if it fails, we will receive a notification no #website-dev so I can quickly check what is happening.
=> chore: trigger coder.com deployment

guides/tls-certificates/cloudDNS.md
We had an outdated installation script for cert-manager
https://cert-manager.io/docs/installation/
We don't have any checks/process in place for checking on this script (ex: parsing it from https://cert-manager.io/docs/installation/). We are prone to getting out of date again without some kind of process around it.
=> fix(tls): cert-manager installation script

guides/tls-certificates/azureDNS.md, guides/tls-certificates/cloudDNS.md, guides/tls-certificates/cloudflare.md, guides/tls-certificates/route53.md
User feedback and known condition that helm install of cert-manager is more reliable. Replaced verbiage.
=> replaced kubeapply jetstack cert-manager approach with helm install

images/configure.md
Feedback in public Slack channel was repository not cloning, based on configure script docs example. Docs were missing the ssh-keyscan command.
=> chore: add ssh-keyscan to configure script example when git cloning

workspaces/editors.md
Finding the new multiple JetBrains IDE docs will be easier if added to the Editors list at the top
=> chore: add multi jetbrains to list at top of editors md

workspaces/devurls.md, workspaces/editors.md
documents Coder's default upload limit of 1MB & logs for code-server & JetBrains IDEs
=> chore: add upload limit & IDE logs

changelog/1.29.0.md
adds a note to our changelog regarding upgrading Projector to version `1.6.0`
=> chore: projector version update

about.md, index.md
This changes the description to explain what Coder does for a more technical audience. I plan to submit future PRs which add more detail to [about.md](https://github.com/coder/docs/blob/main/about.md) to explain some new value props. 
Open to feedback!
=> feat: change Coder description on docs homepage

changelog/1.29.0.md, guides/admin/nfs.md
includes steps for mounting an NFS file share from a server into a Coder workspace. note that this requires CVMs with a FUSE device attached.
also includes a minor addition to the changelog (an RStudio bug fix).
=> feat: NFS file share mounting guide

admin/workspace-management/cvms/images.md
updates our CVM image docs to include adding the `coder` user to the `docker` group.
this is necessary for any non-root user to use Docker, as the Docker Engine is run as `root`.
[sc-22848]
=> chore: add docker group command

manifest.json
re-adds the changelog to manifest, which was removed in the initial reversion
=> chore: add 1.29.2 changelog to manifest

manifest.json
adds the manifest for the NFS guide, which I forgot to include in #938 🤦🏼
=> add: nfs manifest

cli/file-sync.md, workspaces/ssh.md
updates our `mutagen` & `rsync` example commands to sync a specific directory instead of the entire current directory.
=> fix: rsync & mutagen directories

changelog/1.30.0.md
adds cert-injection to `1.30` changelog for self-contained builds. implemented by @Emyrk
=> add: cert injection to 1.30 changelog

setup/kubernetes/openshift.md
When using usermod (or useradd without -l), a sparse file is created
for lastlog/faillog.  The extents of the file scale with the UID, and
Docker does not see the file as sparse, so it will try to generate a
huge image without this patch.
(See https://github.com/moby/moby/issues/5419 for details)
Signed-off-by: Burt Holzman <burt@fnal.gov>
=> chore: Change openshift example to use userdel/useradd instead of usermod

admin/workspace-management/cvms/cluster-setup.md, admin/workspace-management/cvms/index.md, setup/kubernetes/aws.md
adds note regarding selinux limitation and includes AL2 support on the cluster setup page.
=> add: selinux note for CVMs

setup/kubernetes/google.md
A prospect was blocked by the existing GKE install scripts which use Docker-based node images. e.g., ubuntu and cos.
The latest versions of Kubernetes require `containerd`-based node images, so the `image-type` must change to either `ubuntu_containerd` or `cos_containerd`
I also consolidated the machine-type overview, and changed to a more economical e2-standard-4 with nodes with links to general-purpose machine-type docs on Google Cloud.
Reference article (which I linked to in the docs) about the `containerd` change:
https://cloud.google.com/kubernetes-engine/docs/concepts/node-images
=> chore: Setup docs for Kubernetes on Google Cloud - to handle the cloud provider's required node image change from `Docker` to `containerd`

admin/workspace-management/cvms/index.md, setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md, setup/kubernetes/k3s.md
v1 docs still reference the hosted trial in the Kubernetes install docs. I removed those references.
=> chore: remove references to hosted beta

changelog/1.30.4.md, changelog/1.31.2.md, changelog/1.32.2.md, manifest.json
- **yyyy-mm-dd**
- Using Previous Object: `<some-ref>`
- Using Latest Object: `<some-ref>`
=> chore: add release notes for 1.32.2, 1.31.2, 1.30.4

changelog/1.32.1.md
This fix was in 1.32.1 but not shown in the changelog.
=> chore: added dotfiles special character fix to 1.32.1 changelog

admin/workspace-management/cvms/index.md
Another prospect ran into an error running Docker in a CVM workspace.
This doc update should have been done a while ago.
=> chore: added known issue with `containerd` version to work with sysbox and CVMs

setup/kubernetes/azure.md
PR to:
1. Update the Kubernetes Azure install docs to explain the options for allocating IP addresses for Coder pods
=> chore: docs for Azure and IP address planning

manifest.json, setup/kubernetes/rke.md
adds documentation for bringing up a Rancher cluster, with Coder-specific considerations.
feel free to suggest any necessary additions.
=> add: rancher docs

changelog/1.30.0.md, changelog/1.30.1.md, changelog/1.30.2.md, changelog/1.30.3.md, changelog/1.30.4.md, changelog/1.31.0.md, changelog/1.31.1.md, changelog/1.31.2.md, changelog/1.32.0.md, changelog/1.32.1.md, changelog/1.32.2.md, changelog/1.32.3.md, changelog/1.33.0.md, cli/file-sync.md
makes known an issue with JetBrains IDEs version `2022.2` being incompatible with the Projector client/server versions used in Coder releases `1.33.0` & earlier.
=> add: JetBrains IDE/Projector incompatabilities

setup/kubernetes/aws.md
This is PR:
1. Moves a lot of scary info down below about node requirements, prerequisite steps - they are still linked at the top
2. replace the `eksctl` flag argument approach with a config `yaml` file for better readability 
3. remove step for storage class deletion, recreation - I tested, not needed
4. remove 2nd node group creation - the first cluster and node group should be ubuntu to cover CVM use cases too
5. add a cluster delete step
6. general cleanup
My goal is to build an Azure AKS cluster and simplify too.
These steps will be ported and tweaked for OSS once helm is mature so I want to clean old tech debt out of here.
=> chore: refactor aws eks install page - reduce nodes, make ubuntu default

admin/workspace-management/self-contained-builds.md
removes the `remote workspace builds` deprecation notice and adds steps to install the `coderd` TLS cert into the appropriate CA trust store for each distro.
=> rm: remote build deprecation notice & add troubleshooting steps

comparison.md, setup/air-gapped/index.md, setup/architecture.md, setup/requirements.md
v1 docs, in various locations, make it sound it is impossible to evaluate Coder in an air-gapped environment. That is incorrect. Many qualified prospects, typically large organizations, must evaluate Coder in an air-gapped environment.
References are updated to direct inquiries to sales@coder.com to discuss evaluation options since a specific license file type does allow this.
=> chore: provide better path to discuss evaluating coder v1 air-gapped

comparison.md, setup/kubernetes/azure.md
* Cannot set `--network-policy azure` with `--network-plugin kubenet`:
```
(NetworkPolicyAzureNotSupportedForKubenet) NetworkPolicy azure is not supported for network plugin kubenet
Code: NetworkPolicyAzureNotSupportedForKubenet
Message: NetworkPolicy azure is not supported for network plugin kubenet
Target: networkProfile.networkPolicy
```
* Must set the `--node-count` parameter equal to `--min-count` as it appears to default to 0 if unspecified.
=> chore: update az aks create invocation in azure setup docs

manifest.json
We added the doc to explain how to access and configure Offline Docs but did not make it visible. i.e., put the link in the manifest to show on the left tree under Air-Gapped.
=> chore: offline docs were not visible; added to manifest

admin/git.md, admin/workspace-management/limits.md
our docs incorrectly reference an env var as an `integer` rather than a string. the `extraEnvs` value is defined as type `string` in the [core v1 API docs](https://pkg.go.dev/k8s.io/api/core/v1#EnvVar).
=> fix: make env var a string

workspaces/editors.md
this change ensures that the script to enable JupyterLab is executable by Coder upon workspace start.
=> fix: make jupyter binary executable

guides/admin/awsrds.md
I ran into an issue recently when trying to enable this for a new RDS DB Cluster within AWS. My proposed changes are what got me to a working solution with my setup. This included updating the Trust Relationship policy condition to only use the IAM Identity Provider name instead of the full ARN. Also, I ran into a permission issue with a fresh database and my non-admin database user, so I needed to provide an extra grant command to allow the ability to create expressions as part of the initial startup.
=> Updating AWS RDS IAM Auth Documentation

admin/workspace-management/extensions.md
Coder Technologies recently released a new open-source project `code-marketplace` which is a binary to serve VS Code extensions as a custom marketplace to meet air-gapped requirements.
https://github.com/coder/code-marketplace
The project will be enhanced soon with a helm chart and jFrog Artifactory integration.
Docs were updated to reflect this new option, in addition to Open VSX.
=> feat: added the new code-marketplace OSS to serve VS Code extensions air-gapped.

setup/coder-for-docker/local.md
This is an important change since a prospect installed release `1.32.0` which did not support JetBrains latest IDE versions.  We have since fixed that in a `1.33.x` release.
=> chore: update coder for docker release and added a note to check changelog before docker run

setup/air-gapped/index.md, workspaces/editors.md
This PR addresses:
1. Prospect feedback where local VS Code was failing to connect to a Coder workspace using the SSH Remote extension because they were deployed air-gapped. Microsoft has a documented local VS Code settings to upload the server components required versus dialing the Internet. [Article](https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks#:~:text=p%0A%20%20%20%20ControlPersist%20600-,Offline%20remote%20machine,-%23)
2. Incomplete docs for air-gapped extensions marketplaces. Updated a 2nd part of the docs, in the air-gapped setup about using Coder's new OSS `code-marketplace` as an offline VS Code extensions marketplace that can be used in an air-gapped deployment.
=> chore: update air-gap setup to include code-marketplace, and remote SSH IDE with air-gap

workspaces/editors.md
added `/bin` to script location where if run, points to a JetBrains IDE directory for Gateway to use.
=> docs: correct path to jetbrains ide bin path

admin/workspace-providers/deployment/docker.md, admin/workspace-providers/deployment/ec2.md
notes that the ec2 & docker providers are no longer supported. points folks to use v2 for the respective use-cases.
=> deprecate: ec2 & docker providers

changelog/1.36.1.md, manifest.json
For reference here are the two cherry-picks:
```
commit ba917ccc542fd58078a6c61397c275cda28f79a1 (HEAD -> release/1.36, origin/release/1.36)
Author: Jon Ayers <jon@coder.com>
Date:   Sun Nov 13 16:42:31 2022 -0600
fix: prevent regular users from generating arbitrary API keys (#13355)
- Fixes a bug where a user can generate a key for an arbitrary user
assuming they have a reference to the user ID.
commit 769c61a5db9a5a9130b689158dc4c7cb82cf30be
Author: Spike Curtis <spike@coder.com>
Date:   Thu Oct 27 09:13:02 2022 -0700
Use client TLS certs for Gitlab token refresh, if available (#13261)
```
=> Added 1.36.1 changelog

workspaces/editors.md
This PR:
1. Removes docs and examples for JetBrains projector, the suspended OSS project to access JetBrains IDEs in a browser
=> chore: remove jetbrains projector web ide docs in v1, examples. specify no support

cli/index.md
Coder v2 users looking for the CLI often land on a Google search result which is the Coder v1 CLI, which will not work with a Coder v2 deployment.
Updated the Coder v1 docs page to clearly state this is for Coder v1 and provide a link to the Coder v2 CLI docs if they landed on the document by accident.
This has happened on several occasions where support calls with Coder personnel only uncover the mistake.
=> docs: explicitly point out the CLI is for Coder v1 and a link to v2

workspaces/ssh.md
The previous command example with `user@coder.<workspace>` does not work and gives a `fatal: failed to find workspace` error.
=> Correct rsync command

cli/index.md
this PR reverts my commit which used a markdown link inside of HTML. reverting back to the correct `<href>` syntax.
=> revert & fix: docs cli notice

admin/workspace-management/ssh-access.md, workspaces/vs-code-extensions.md
We would like to get this shut down.
Also the environment variable changed a long while back.
=> Remove mention of legacy extension marketplace
