manifest.json
=> chore: Place changelog nav entry below admin

changelog/1.13.2.md, changelog/1.14.0.md, changelog/1.14.1.md, changelog/1.14.2.md
=> feat: Add date description to each release

environments/editors.md
=> fix: add reference to 1-way file sync

environments/lifecycle.md
=> fix: Clarify rebuild home persistence [#46]

environments/editors.md
[ch5978] - Document manual install of JetBrains IDEs on coder environment
=> Document manual install of JetBrains IDEs

admin/environment-management/ssh-access.md
=> feat: add docs on OpenSSH support

admin/extensions.md
=> feat: remove reference to internal marketplace

admin/devurls.md, manifest.json, setup/configuration.md, setup/index.md, setup/installation.md, setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md, setup/kubernetes/index.md
* Ported K8 docs from Zendesk and updated with better instructions
* Modified Install and Config guides so that the former gets you all the way through accessing Coder from the browser. Also added brief helm chart instructions.
=> chore: port, reorg K8, install/setup docs

comparison.md, setup/configuration.md, setup/index.md
Fixes lint issues introduced in https://github.com/cdr/docs/pull/103
=> chore(docs): Format

admin/api.md
add info on auth reqs to use public api
=> chore: add auth requirements for public API

comparison.md
Removed outdated information about previous free trial.
=> Update Comparison Chart

guides/teardown.md
small change to add code formatting to the helm command.
=> fix: command formatting

setup/installation.md
For [CH #8118](https://app.clubhouse.io/coder/story/8118/clarify-how-to-create-postgresql-password-secret-in-installation-instructions)
=> Update PostgreSQL secret instructions

setup/requirements.md
Removed material that applied to the previous trial program.
=> Updated to reflect new Coder trial program

setup/installation.md
context - customer installing a trial asked how he should set his `values.yaml` file (Step 3b) if he is setting up a bare-bones demo instance. thought I'd clarify that steps 3-5 aren't necessary for non-prod deployments.
=> clarify: installation steps

guides/helm-charts.md, manifest.json
[Preview](https://codercom-r412dtswg-codercom.vercel.app/docs/guides/helm-charts)
=> chore: add doc on modifying helm charts

setup/updating.md
This PR clarifies the `updating` steps by being explicit in ensuring you retain your current values in your helm installation.
Change visible in preview deployment:
=> Chore: Clarify updating steps to include values override

setup/index.md
=> chore: add further nav aids to setup index

setup/kubernetes/local-preview.md
Documents the fix for an obscure build issue using CVMs in Kind
=> chore: document expanded requirements for CVMs in local preview

setup/updating.md
https://helm.sh/docs/helm/helm_delete/ says the
delete command was renamed to uninstall 
so the note is unnecessary.
=> Correct helm delete command

changelog/1.17.0.md
In draft until release manage approves
=> clog: Add dormancy bug fix to 1.17 clog

guides/ssl-certificates/cloudflare.md, setup/updating.md
Some fixes based on my experience upgrading today.
=> Upgrade docs fixes (helm values, remove --force)

.github/dependabot.yml
=> chore: add dependabot to manage dependencies

README.md
Oopsies. This is blocking @ericpaulsen on #217
=> fix: README fmt

.husky/post-checkout
LMK if you think we should add the `yarn.lock` check. I didn't feel compelled to because this project is small enough, but happy to modify if we prefer it
=> chore: Add post-checkout hook

changelog/1.17.2.md, environments/workspaces-as-code/templates.md
**Primary issue**:
The sample template has an incorrect structure for `configure`
**Secondary issue**: 
Inconsistent use of periods at the end of bullet points 🤷
=> WAC release fixups

setup/air-gapped.md
Added a CTA to allow users to request a pilot if they require an air-gapped deployment.
=> chore: add CTA to request pilot

environments/workspaces-as-code/templates.md
from CH10176: https://app.clubhouse.io/coder/story/10176/sample-wsac-template-doesn-t-work
The example template in Workspaces as Code doesn't use the new configure.start: https://coder.com/docs/environments/workspaces-as-code/templates#workspace-template-sample
```sh
➜  wsac-test coder envs create-from-config -f coder.yaml --name demo --org=Primary
error: Bad YAML
| Unable to parse yaml: yaml: unmarshal errors:
line 21: cannot unmarshal !!seq into envtemplate.configure
```
```yaml
version: 0.1
workspace:
type: kubernetes
spec:
image: index.docker.io/ubuntu:18.04
container-based-vm: true
cpu: 4
memory: 16
disk: 128
gpuCount: 1
labels:
com.coder.custom.hello: "hello"
com.coder.custom.world: "world"
tolerations:
- key: my-key
operator: Equal
value: my-value
effect: NoExecute …
```
=> fix WSAC examples

cli/installation.md, setup/requirements.md
updating auth language, as we now ask the user to paste a session token from their browser.
=> update CLI login & grammer tweak

setup/updating.md
submitting this PR, as we received feedback from a customer that we should tweak our docs on `helm uninstall` to clarify what is removed & preserved when running this command. I've tested this on my end to ensure the updates added in this PR are correct.
=> clarify helm uninstall

setup/air-gapped.md
Fixes https://app.clubhouse.io/coder/story/10588/remove-reference-to-built-in-extension-marketplace
=> chore: update VS Code extensions marketplace recommendation

changelog/1.17.1.md, changelog/1.17.2.md, changelog/1.17.3.md
I generated these dates using the command-line utility `date`. I must've used an incorrect formatter
=> fix(clog): Clog date formats dd -> dddd

admin/environment-management/cvms.md, changelog/1.17.3.md, changelog/1.17.4.md, manifest.json
=> Release 1.17.4

admin/registries/index.md
AWS ECR: https://app.clubhouse.io/coder/story/2616/customer-amazon-elastic-container-registry-ecr-integration
GitHub Packages: https://app.clubhouse.io/coder/story/8094/use-tagged-images-and-avoid-imagepullpolicy-always
=> mention unsupported registries

guides/customization/vnc.md, manifest.json
Creating this PR to outline steps for accessing a VNC through Coder. I've pulled down [this image](https://github.com/cdr/enterprise-images/blob/ed66817dfa83e33132322c33bea653a8a5fdc057/images/vnc/Dockerfile.ubuntu), built & pushed it to Docker Hub, and successfully spun it up in Coder. I would like Product's eyes on this to validate the contents of this doc and add context where necessary. This is needed by Thursday for a strategic customer.
I've added comments in areas I need some clarification on.
[related clubhouse story](https://app.clubhouse.io/coder/story/10814/create-vnc-documentation)
=> add: VNC documentation

environments/editors.md
For [CH#10227](https://app.clubhouse.io/coder/story/10227/document-coder-jetbrains-dependencies)
=> chore: link to JetBrains install instructions

guides/admin/resources.md
fixes [CH#10657](https://app.clubhouse.io/coder/story/10657/contented-should-be-contended)
=> chore: fix typo in admin resources doc

package.json
Add project name, description, homepage, bugs, license, and
private project settings to the package.json file.
=> chore: update metadata in package.json

guides/deployments/postgres.md, manifest.json, setup/installation.md
adding docs for hooking up an external (to the cluster) postgres, as it is our recommended approach for production Coder deployments.
this is intended as an MVP, as I expect us to iterate on this as we continue to get customer feedback. open to thoughts & suggestions.
=> feat: connecting an external postgres

setup/kubernetes/aws.md, setup/kubernetes/azure.md, setup/kubernetes/google.md, setup/requirements.md
Update suggested resource allocations for Coder deployments
=> chore: modify K8s requirements

guides/ssl-certificates/cloudDNS.md
[Preview](https://codercom-gnu91r0kk-codercom.vercel.app/docs/guides/ssl-certificates/cloudDNS)
=> chore: fix typos, formatting issues with Cloud DNS doc

setup/requirements.md
adding this note on DVP, as Coder assumes it to be enabled to provision a new workspace & mount the PVC. feel free to leave feedback & wordsmith.
=> add note on dynamic volume provisioning

.all-contributorsrc
quick update to my profile URL
=> update profile with personal site

workspaces/workspaces-as-code/templates.md
Also add "type" to the provider comment
=> configure add git clone example

changelog/index.md, setup/installation.md
adding context to release candidates, and when they should be used.
=> clarify rc usage

manifest.json
Related to: https://github.com/cdr/m/pull/8601
=> chore: add versions to manifest.json

setup/kubernetes/google.md
fixing link on google setup that sent user to Microsoft docs...
=> fix google node sizing link

guides/troubleshooting/docker-problems.md, manifest.json
@khorne3 I left some really poor english, and not a ton of insight here. Feel free to entirely refactor, reword, or rewrite the whole thing.
We ran into this problem with many users packed on the same instance... if you'd like better elaboration just let me know!
=> chore: Add solution for Docker problems

workspaces/workspaces-as-code/templates.md
Draft until the conversation about if this is feature flagged.
=> Add docs for nodeSelector and tolerations

scripts/add_clog_to_manifest.ts
Updated to match package.json:
https://github.com/cdr/docs/blob/94ce5fde382a2967affc03c247f5a0423e14fdc1/package.json#L13
=> chore: Fix format tip in add_clog_to_manifest

setup/requirements.md
adding a recommendation for resource allocation, as discussed in this [clubhouse thread].(https://app.clubhouse.io/coder/story/12852/k8s-sizing-recommendations)
[ch 12852]
=> add resource recommendation

admin/templates.md
This PR documents the fields that can be applied to template policies, as well as the behavior of the template policy on custom workspaces and workspaces that have conflicting values.
=> add detail to site-wide template policy doc

.github/workflows/preview.yaml
The docs checkout step is not necessary anymore.
=> Remove checkout docs

setup/requirements.md
updating our storage requirements, as prospects & customers have ran into pod eviction issues due to node disks being too small.
=> add node disk sizing recommendation

guides/admin/oidc-okta.md
minor edits to existing Okta content
=> chore: edit Okta content

.github/workflows/production.yml
This workflow is based on https://github.com/cdr/m/blob/master/.github/workflows/codercom.yaml#L83 and https://github.com/cdr/docs/blob/main/.github/workflows/preview.yaml#L21. I removed the DatoCMS update since this is not related to it at all.
PS: Idk how would be the best way to test this action though.
=> Add production workflow

getting-started.md, guides/ssl-certificates/cloudDNS.md, manifest.json
This begins adding the `Getting Started` doc to the docs repo.
@khorne3 I've not added it to the manifest as I wasn't sure where you wanted it to live. Would love an initial review and we can iterate from here!
=> Add Getting Started Doc

images/configure.md
Minor fixed based on customer confusion -- we had this info super buried
=> chore: expand instructions on creating a configure file

setup/kubernetes/local-preview.md
This uses the same limitation message as the [k3s](https://github.com/cdr/docs/blame/main/setup/kubernetes/k3s.md#L20) docs.
=> local preview: further clarify limitation

setup/kubernetes/local-preview.md
=> Revert "local preview: add instructions for dev urls"

admin/satellites/migration.md
There's a bug in this flow that is hard to recover from, removing for now so no one fall into it and will add back new docs ASAP
=> remove instructions around helm uninstall

admin/satellites/migration.md
These are more appropriate final steps for migrating to satellites
=> Add notes about next steps in satellite migration

guides/admin/oidc-azuread.md
@IAmHughes if there are other take-always, toss them in here.
=> Specify single tenant AD

admin/workspace-management/installing-jetbrains.md, workspaces/editors.md
https://github.com/cdr/m/pull/9426
=> feat: Add Android Studio support

setup/updating.md
[Preview](https://codercom-4z3kbvwnq-codercom.vercel.app/docs/coder/v1.21/setup/updating)
=> chore: expand upgrade instructions for 1.21

setup/kubernetes/aws.md
=> Update ubuntu ami version

setup/kubernetes/index.md
context: a few users have tried Coder with DigitalOcean Kubernetes, only to find that CVMs are unsupported.
=> document incompatible k8s distributions

workspaces/getting-started.md
Keeping the docs in sync with https://github.com/cdr/m/pull/9905
=> Update status from decommissioned to deleting

.github/workflows/ci.yaml, .github/workflows/preview.yaml
=> fix issue w/ preview config

cli/installation.md
Just cherry-picking the commit from the previous review!
=> docs: cli: add information about coder update command (#606)

setup/kubernetes/index.md
removing extra whitespace from setup/k8s index
=> chore: remove whitespace

changelog/1.24.0.md
removing since there's no user-level setting yet
=> chore: remove mention of ws auto-off

guides/troubleshooting/inotify-watch-limits.md
Related to internal slack thread: https://codercom.slack.com/archives/C01AULWQW68/p1634584479176200
=> Increase inotify watchers in docs

images/configure.md
This catches people out all the time; it's a good idea to provide a note about this.
=> chore(docs): configure: add note about sudo -E

setup/docker.md
We currently don't publish to :latest
=> add version tag

setup/docker.md
fix addresses issue when creating dev URLs
[sc-19341]
=> fix c4d command typo

workspaces/applications.md
updating doc to include actual examples of images/config files
=> chore: add applications sample usage

setup/air-gapped/index.md
making this change to include the [example helm values](https://github.com/coder/enterprise-helm/blob/main/examples/offline/offline.values.yaml) created by @jawnsy. [slack thread here](
https://codercom.slack.com/archives/C0102H1BBKK/p1640115155082700).
=> chore: update air gapped deploy command & values

comparison.md
Added additional Coder features
Updated air-gapped evaluation procedure to what is current
=> updated comparison with recent data on Coder enhancements

guides/deployments/postgres.md, setup/installation.md
adding note to check for trailing white spaces in db passwords
[sc-20033]
=> chore: add whitespace warning

setup/air-gapped/index.md
quick fix to the incorrect numbering displayed as a result of #787.
=> fix: numbering

getting-started/admin.md, getting-started/index.md, index.md, manifest.json
- simplified `index.md` to draw attention to contents of the section
- moved a lot of the existing content on `index.md` to `admin.md`
=> chore: update Getting Started landing page

guides/troubleshooting/vite-hmr.md, manifest.json
Adds a guide for troubleshooting vite and HMR
=> docs: add vite-hmr guide

admin/workspace-management/process-logging.md
=> chore: add cloudwatch example query for process logs

images/writing.md
removes incorrect `CLion` references and generalizes the section heading. also fixes IDE installation URL.
=> fix: custom JetBrains image

guides/deployments/podman.md
When copying the yaml and pasting it into a file, I was getting validation errors when trying to apply. The yaml was a little misaligned.
=> Format yaml for deploying smarter-device-manager

guides/deployments/podman.md
@jawnsy let me know if this isn't what you had in mind!
=> chore: add link to Podman limitations list

guides/deployments/podman.md
fixes yaml syntax in the podman workspace template.
=> fix: podman yaml template

images/writing.md, setup/requirements.md, workspaces/editors.md
removes explicit requirements around workspaces using JetBrains IDEs. also fixes the header in `Custom Image Creation`. this was missed in #811.
=> chore: clean up JetBrains resource requirements

admin/access-control/index.md
fixes a broken link on our access control page.
=> fix: site manager URL

setup/kubernetes/aws.md
further reading: https://eksctl.io/usage/custom-ami-support/
=> fix: clarify custom AMI usage with eksctl

setup/docker.md
Added some documentation about Rosetta to emulate x86-64:
=> chore: add information about Apple Silicon machines

setup/docker.md
I made a note on the release tasklist to update these, too
=> chore: update Docker versions

setup/docker.md
=> Update Coder for Docker version

admin/stun.md
depends on https://github.com/coder/m/pull/12191
=> chore: remove usage of P2P

workspaces/personalization.md
Not sure if this is sufficient or if we want to explain more.
=> chore: add info about setting env vars in .profile

changelog/1.28.0.md
=> fix: link to version support policy

workspaces/lifecycle.md
The previous intro was poorly worded with spelling and grammar mistakes.
=> updated lifecycle page

workspaces/preferences.md
Added documentation for when customers use additional authentication to their Git provider.
=> updated Linked Accounts for VPN scenario

workspaces/preferences.md
Starting in v1.29, the Notifications preference page is removed.
=> fix(workspaces): modify notifications [FF]

workspaces/workspace-templates/index.md
Part 2 to documenting templates and C4D. I added a reference to C4D docs on this topic in the templates docs.
=> add c4d template link to the templates section

images/configure.md, images/embed-button.md, images/importing.md, images/index.md, images/writing.md, manifest.json
Updated the images docs sections with commonly asked questions and clarifications that have assisted customer deployments.
=> chore: refreshed images section, with deployment best practices

admin/access-control/manage.md
adds detail on the OIDC claims Coder expects.
=> feat: OIDC claims

admin/access-control/manage.md, workspaces/pwa.md
denotes HTTPS requirement for PWAs and clarifies OIDC claim requirements
=> chore: add HTTPS req for PWA & update OIDC claims

workspaces/editors.md
Got Slack feedback that latest RStudio versions not working with our current RStudio docs.  Updated Dockerfile and tested the latest RStudio version and it worked fine.
=> chore: updated RStudio Dockerfile

admin/workspace-management/shutdown.md
Added clarity to when auto-off will not occur.
=> chore: add exceptions to auto-off

setup/installation.md
=> chore: remove mention of doctor

admin/access-control/index.md
adds info on the default user session expiration.
=> add: default user session expiration

changelog/1.28.5.md, manifest.json
* chore: add changelog for 1.28.5
* fixup! chore: add changelog for 1.28.5
* Update changelog/1.28.5.md
Co-authored-by: Katie Horne <katie@coder.com>
(cherry picked from commit fb556656efe837cba0dd1241d6b74f1c3fc1142a)
=> chore: add changelog for 1.28.5 (#960)

changelog/1.29.3.md, manifest.json
(cherry picked from commit 2222dada2a63700ce7f3638bf73c3e19df5523b5)
=> chore: add changelog for 1.29.3 (#961)

getting-started/intellij.md
=> rm: VS Code instructions

workspaces/ssh.md
[Slack msg for context](https://codercom.slack.com/archives/C014JH42DBJ/p1651694506464609)
=> chore: update SSH doc

setup/requirements.md
adds note to schedule nodes in each AZ in use to prevent volume node affinity conflicts.
[sc-23198]
=> chore: address volume node affinity conflicts

setup/installation.md, setup/upgrade/index.md
adds values for configuring a proxy with `coderd`, and also updates the page formatting, as to better allow for linking to specific steps.
also includes a minor addition to the Upgrades page, noting that downgrading (without a database snapshot) is not supported.
=> add: install formatting & proxy config

admin/prometheus.md, manifest.json
initial commit to add documentation on setting up Prometheus to connect to `coderd`
[sc-22667]
=> add: prometheus docs

admin/organizations/index.md
Removed unnecessary semicolon on line 20 and replaced it with a period.
=> Update Organizations docs page (v1)

guides/admin/awsrds.md, setup/installation.md
documentation for using the `awsrds` postgres connector in our Helm chart. reference's @f0ssel's PR - https://github.com/coder/m/pull/11498
=> add: aws rds iam docs

guides/admin/logging.md
Removed unnecessary period on line 93
=> Update Logging docs page (v1)

admin/audit.md
Removed periods on lines 44 and 57 to maintain consistency with the rest of the passage
=> Update audit logs v1 documentation

admin/templates.md
=> small typo - Update templates.md

manifest.json
adds in the manifest that i forgot to add in #1046
=> add: aws rds manifest

admin/organizations/manage.md
Added periods to the ends of the sentences on lines 24 and 26 to maintain consistency with the rest of the passage; also removed an unnecessary comma from line 32.
=> Update Org management docs page (v1)

setup/installation.md
minor fix to address incorrect numbering.
=> fix: numbering & indentation

changelog/1.32.3.md
The Projector updates should resolve this issue.
=> changelog/1.32.3: remove known issue regarding 2022.2 jetbrains IDE versions

admin/git.md
for next 1.33 patch (main: https://github.com/coder/docs/pull/1085)
=> chore: docs: document CODERD_BITBUCKET_CONSUMER_KEY

setup/installation.md
This commit adds a warning regarding Coder's hard dependency on its PostgreSQL database.
EDIT: `prettier` also apparently decided 2 spaces now instead of 4. 🤷
=> chore: add warning about database availability

changelog/1.33.3.md, manifest.json
kinda a cherry pick to the specific branch
=> chore: add changelog 1.33.3

changelog/1.32.4.md, manifest.json
=> chore: add changelog 1.32.4

admin/workspace-management/installing-jetbrains.md, changelog/1.31.3.md, changelog/1.32.3.md, changelog/1.32.4.md, changelog/1.33.1.md, changelog/1.33.2.md, changelog/1.33.3.md
=> chore: add note about JetBrains IDE versions

setup/coder-for-docker/local.md, setup/coder-for-docker/postgres.md, setup/coder-for-docker/upgrade.md
this PR fixes our Docker Compose YAML indentation for Coder for Docker, and also adds a Postgres container to the YAML example.
=> fix: c4d docker compose

changelog/1.34.0.md
adds a changelog note for https://github.com/coder/enterprise-helm/pull/262
=> add: helm chart verbose toggle

changelog/1.33.5.md, manifest.json
=> chore: update changelog for 1.33.5

guides/moving-to-oss.md
We'll be keeping this document up-to-date as a tracker for v1->v2 features
=> moving to OSS: dind and audit logging are complete

workspaces/workspace-templates/templates.md
Documentation for coder/v1#13002
=> feat: add docs for seccompProfile workspace template fields

changelog/1.35.0.md
(cherry picked from commit 63bc83d715dd78808838551d809e07d27ce93552)
=> Update 1.35.0.md (#1134)

workspaces/workspace-templates/templates.md
Documentation for coder/v1#13052 and coder/v1#13106
=> feat: document run-as-user and run-as-group

changelog/1.35.1.md, manifest.json
(cherry picked from commit ec6595cdcea3c21370c59d3b58487854fc093ff9)
=> [v1.35 cherry] chore: add changelog for 1.35.1 (#1139)

changelog/1.34.1.md, manifest.json
* chore: add changelog for 1.34.1
* fixup! chore: add changelog for 1.34.1
(cherry picked from commit 6efc276f98d975648b0acf2d9bafa76c35b77df2)
=> [v1.34 cherry] chore: add changelog for 1.34.1 (#1140)

admin/audit.md
adds tables for the expected outputs of admin setting changes in the audit log.
=> add: admin field/audit log mappings

admin/access-control/manage.md
Fixes https://github.com/coder/docs/issues/1145
=> chore: document OIDC scopes requested by Coder

setup/upgrade/considerations.md
adds an upgrade consideration for folks upgrading to 1.30 & beyond.
=> add: 1.30 db migrations note

changelog/1.33.6.md, manifest.json
=> Added changelog for 1.33.6

changelog/1.34.2.md, manifest.json
=> Add 1.34.2 changelog

setup/kubernetes/openshift.md
based on feedback from a customer using OpenShift.
=> fix & clarify: openshift SCC

guides/admin/timescale-migration.md
removes the requirement for the TimescaleDB extension in PostgreSQL.
=> rm: timescaleDB requirement

changelog/1.35.3.md, manifest.json
=> Changelog for 1.35.3

changelog/1.34.3.md, manifest.json
=> Changelog for 1.34.3

admin/security.md, guides/troubleshooting/ssh-no-mutual-signature-supported.md, manifest.json
Fixes https://github.com/coder/v1/issues/13259
=> Document ssh no mutual signature supported

guides/deployments/postgres.md
=> Add docs explaining max postgres connections

changelog/1.36.2.md, manifest.json
=> 1.36.2 changelog

changelog/1.35.4.md, manifest.json
=> Add 1.35.4 changelog

guides/deployments/podman.md
added based on feedback from a prospective customer.
=> add: podman docs to podman guide

guides/v2-faq.md
duplicate 'in' in the sunset table
=> Docs v2 faq tweaks

setup/kubernetes/openshift.md
Updated the sample Dockerfile to include steps for adding a group from the SCC UID range.
=> chore: update openshift docs for building custom images

admin/git.md
Fixes https://github.com/coder/v1/issues/13303
=> Docs for Bitbucket 7.20+
